[package]
name = "fmi_largest_set"
version = "0.1.0"
authors = ["Felix Buehler <account@buehler.rocks>"]
edition = "2018"

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
rayon = "1.5"
