[package]
name = "mlp_merge"
version = "0.1.0"
authors = ["Felix Buehler <account@buehler.rocks>"]
edition = "2018"

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
rand = "0.9"
rayon = "1.8"
ordered-float = "5.0"
