name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Install glpk
      run: sudo apt-get install libglpk-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
